#!/usr/bin/env bash

set -euo pipefail

DESKTOP_DIR="$HOME/.local/share/applications"
ICON_DIR="$HOME/.local/share/applications/icons"

mkdir -p "$DESKTOP_DIR" "$ICON_DIR"

read -p "Name App : " APP_NAME
read -e -p "Path Appimage : " APP_PATH
