#!/usr/bin/env bash

set -euo pipefail

ICON_DIR="$HOME/.local/share/applications/icons"
DESKTOP_DIR="$HOME/.local/share/applications"

if command -v chromium >/dev/null; then
  BROWSER="chromium"
elif command -v google-chrome >/dev/null; then
  BROWSER="google-chrome"
else
  echo "No supported browser found"
  exit 1
fi

read -p "Name App : " APP_NAME
read -p "URL App : " APP_URL

if ! [[ "$APP_URL" =~ ^https?://[^/]+ ]]; then
  echo "Invalid URL format"
  exit 1
fi

if [[ ! $APP_URL =~ ^[a-zA-Z][a-zA-Z0-9+.-]*: ]]; then
    APP_URL="https://$APP_URL"
fi
