#!/usr/bin/env bash

set -euo pipefail

DIR="$HOME/Pictures/Screenshots"
mkdir -p "$DIR"

FILENAME="$(date +"%Y-%m-%d_%H%M%S").png"
FULLPATH=$DIR/$FILENAME

if [[ ${XDG_SESSION_TYPE:-} != "wayland" ]]; then
  notify-send "Session must wayland"
fi
