#!/usr/bin/env bash

set -euo pipefail

DESKTOP_TRACK_NAME="Game"
MIC_TRACK_NAME="Mic"

if [[ "$#" -lt 1 ]]; then
  echo "Error: Requires at least 1 argument"
  echo "Usage: $0 <file_path>"
  exit 1
fi

VIDEO_DIR=$1

if [[ ! -f "$VIDEO_DIR" ]]; then
  echo "Error: File not found -> $VIDEO_DIR"
  exit 1
fi

FULLPATH=$(realpath "$VIDEO_DIR")
BASENAME=$(basename "$FULLPATH" .mkv)
OUTPUT_DIR="$HOME/Videos/Recordings"
mkdir -p "$OUTPUT_DIR"

VIDEO_GAME_OUTPUT="$OUTPUT_DIR/${BASENAME}_game-video.mp4"
AUDIO_GAME_OUTPUT="$OUTPUT_DIR/${BASENAME}_game-audio.m4a"
MIC_OUTPUT="$OUTPUT_DIR/${BASENAME}_mic.wav"
